---
title: "Lifestyle Habits and Work Productivity Analysis"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
df <- read_csv("data.csv")
head(df)
```

```{r}
summary(df)
str(df)
```

```{r}
colSums(is.na(df))
```

```{r}
df <- df %>% rename(
  "ID" = "Person_ID",
  "Sleep Start" = "Sleep Start Time",
  "Sleep End" = "Sleep End Time",
  "Sleep Hours" = "Total Sleep Hours" ,
  "Exercise Time" = "Exercise (mins/day)",
  "Caffeine" = "Caffeine Intake (mg)",
  "Screen Time" = "Screen Time Before Bed (mins)",
  "Work Hours" = "Work Hours (hrs/day)",
  "Prod Score" = "Productivity Score",
  "Mood" = "Mood Score",
  "Stress" = "Stress Level"
)
```

```{r}
length(unique(df$ID))
```

```{r}
counts <- table(df$ID)
counts[counts > 3]
```

```{r}
df[df$ID %in% c(5597),]
```

```{r}
df <- df %>% select(-`ID`, -`Date`)
head(df)
```

```{r}
ggplot(df, aes(x = `Prod Score`)) +
  geom_histogram(binwidth = 1, fill = "cyan", color = "black", alpha = 0.5) +
  scale_x_continuous(breaks = 1:10) +
  labs(
    title = "Productivity Score", x = "Productivity Score", y = "Frequency")
```
```{r}
ggplot(df, aes(x = `Age`)) +
  geom_histogram(binwidth = 1, fill = "pink", color = "black", alpha = 0.5) +
  labs(title = "Age", x = "Age", y = "Frequency")
```
```{r}
ggplot(df, aes(x = `Sleep Hours`)) +
  geom_histogram(binwidth = 1, fill = "orange", color = "black", alpha = 0.5) +
  labs(title = "Sleep Hours", x = "Sleep Hours", y = "Frequency")
```
```{r}
ggplot(df, aes(x = `Gender`)) +
  geom_histogram(stat = "count", fill = "purple", color = "black", alpha = 0.5) +
  labs(title = "Gender", x = "Gender", y = "Frequency")
```
```{r}
ggplot(df, aes(x = `Sleep Quality`)) +
  geom_histogram(binwidth = 1, fill = "green", color = "black", alpha = 0.5) +
  scale_x_continuous(breaks = 1:10) +
  labs(title = "Sleep Quality", x = "Sleep Quality", y = "Frequency")
```
```{r}
ggplot(df, aes(x = `Mood`)) +
  geom_histogram(binwidth = 1, fill = "yellow", color = "black", alpha = 0.5) +
  scale_x_continuous(breaks = 1:10) +
  labs(title = "Mood", x = "Mood", y = "Frequency")
```
```{r}
ggplot(df, aes(x = `Stress`)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black", alpha = 0.5) +
  scale_x_continuous(breaks = 1:10) +
  labs(title = "Stress Level", x = "Stress Level",y = "Frequency")
```

```{r}
ggplot(df, aes(x = `Mood`, y = `Stress`)) +
  geom_point(color="red", size = 3) +
  scale_x_continuous(breaks = 1:10) +
  labs(title = "Mood v/s Stress", x = "Mood", y = "Stress")
```
```{r}
library(ggcorrplot)
corr_mat = round(cor(df[sapply(df, is.numeric)]),1)
ggcorrplot(corr_mat, lab = TRUE)
```
```{r}
ggplot(df, aes(x = `Work Hours`, y = `Prod Score`)) +
  geom_point(col = 'green') +
  geom_smooth(method = "loess", col = 'red')
```
```{r}
df$`Work Hours` = round(df$`Work Hours`)
df_summary <- df %>%
  group_by(`Work Hours`) %>%
  summarise(mean_prod = mean(`Prod Score`, na.rm = TRUE))

# Plot
ggplot(df_summary, aes(x = `Work Hours`, y = mean_prod)) +
  geom_line(color = "green") +
  geom_point(color = "red") +
  labs(title = "Mean Productivity Score by Age",
       x = "Age",
       y = "Mean Productivity Score")
```
```{r}
df_summary <- df %>%
  group_by(`Age`) %>%
  summarise(mean_prod = mean(`Prod Score`, na.rm = TRUE))

# Plot
ggplot(df_summary, aes(x = `Age`, y = mean_prod)) +
  geom_line(color = "green") +
  geom_point(color = "red") +
  labs(title = "Mean Productivity Score by Age",
       x = "Age",
       y = "Mean Productivity Score")
```
```{r}
df$Caffeine = round((df$Caffeine / 10)) * 10
df_summary <- df %>%
  group_by(`Caffeine`) %>%
  summarise(mean_prod = mean(`Prod Score`, na.rm = TRUE))
ggplot(df_summary, aes(x = `Caffeine`, y = mean_prod)) +
  geom_line(color = "green") +
  geom_point(color = "red") +
  labs(title = "Productivity Score by Caffeine Intake",
       x = "Caffeine",
       y = "Mean Productivity Score")
```
```{r}
df_summary <- df %>%
  group_by(`Caffeine`) %>%
  summarise(mean_sleep_duration = mean(`Sleep Hours`, na.rm = TRUE))
ggplot(df_summary, aes(x = `Caffeine`, y = mean_sleep_duration)) +
  geom_line(color = "green") +
  geom_point(color = "red") +
  labs(title = "Sleep Hours by Caffeine Intake",
       x = "Caffeine",
       y = "Mean Sleep Hours")
```
Hypothesis Testing:
 
H0: Mean productivity of people sleeping <5 hrs is not < Overall average productivity

H1: Mean productivity of people sleeping <5 hrs < Overall average productivity
```{r}
sleep_less_than_5 <- subset(df, df$`Sleep Hours` < 5)
t.test(sleep_less_than_5$`Prod Score`, mu = mean(df$`Prod Score`), alternative = 'less')
```
H0: Mean productivity (sleep >5 hrs) = Mean productivity (sleep <5 hrs)

H1: Mean productivity (sleep >5 hrs) > Mean productivity (sleep <5 hrs)
```{r}
more_than_5 = subset(df, df$`Sleep Hours`>5)
less_than_5 = subset(df, df$`Sleep Hours`<5)
t.test(more_than_5$`Prod Score`, less_than_5$`Prod Score`, var.equal = TRUE, alternative = 'greater')
```
 
```{r}
df <- df %>%
  mutate(`Riser Type` = case_when(
    `Sleep End` < 4 ~ "Sleep Disorder",
    `Sleep End` < 7 ~ "Early Riser",
    TRUE ~ "Late Riser"
  ))
anova_result <- aov(df$`Prod Score` ~ df$`Riser Type`, data = df)
summary(anova_result)
```
```{r}
TukeyHSD(anova_result)
```